/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/user/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with email and password
         * @description Sets `csrftoken` and `sessionid` cookies on success. Caller must first
         *     GET any HTML page (e.g. `/no/user/login/`) to obtain a CSRF cookie.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        username: string;
                        /** Format: password */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Authenticated; session cookies set on response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid credentials */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/no/search/products/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Product search (HTML page with embedded JSON)
         * @description Returns an HTML page. Product results are embedded in the
         *     `__NEXT_DATA__` script tag under
         *     `props.pageProps.dehydratedState.queries[]`, where `queryKey[0]._id`
         *     is `"mixedSearch"` (or legacy `"searchpageresponse"`). Each `items[]`
         *     entry has `type: "product"` (others — categories, banners — should
         *     be skipped).
         */
        get: {
            parameters: {
                query: {
                    /** @description Search query (Norwegian or English) */
                    q: string;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description HTML page; relevant payload is in `__NEXT_DATA__` */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current cart */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cart contents */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cart"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart/items/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mutate cart items (signed delta)
         * @description Positive `quantity` adds, negative removes. Negative beyond zero
         *     clamps at zero (item disappears).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        items: components["schemas"]["ItemDelta"][];
                    };
                };
            };
            responses: {
                /** @description Updated cart */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cart"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List past orders, grouped by month, newest first */
        get: {
            parameters: {
                query?: {
                    /** @description Pagination cursor; passed back in `get_more_url`. */
                    "through-date"?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Orders grouped by month */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrdersResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_number}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one order with line items */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 5fdnhy */
                    order_number: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Order detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderDetail"];
                    };
                };
                /** @description Unknown order */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart/recurring/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consumer recurring cart (do not use on B2B)
         * @description Same shape as `/api/v1/cart/`. On B2B accounts this always returns
         *     the empty cart shape (`product_quantity_count: 0`) even when an
         *     active recurring order exists. The B2B recurring order lives under
         *     `/api/v1/product-lists/` instead.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recurring cart */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cart"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart/recurring/items/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mutate consumer recurring cart (do not use on B2B)
         * @description Same protocol as `/api/v1/cart/items/`. Signed delta.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        items: components["schemas"]["ItemDelta"][];
                    };
                };
            };
            responses: {
                /** @description Updated recurring cart */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cart"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product-lists/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the user's product lists (paginated)
         * @description On a B2B account, the *active recurring order* is the entry whose
         *     `recurring_order.is_active` is true. Schedule details (cadence,
         *     weekday, next delivery date) are attached to that entry.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of product lists */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductListsPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product-lists/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a product list with full items */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Product list with items */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductList"];
                    };
                };
                /** @description Unknown list */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product-lists/{id}/products/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mutate a product list (signed delta)
         * @description Body is a *top-level array* (not `{ items: [...] }` like the cart).
         *     Positive `quantity` adds (or creates an entry), negative removes.
         *     Negative beyond zero clamps at zero. Adding to a list that has an
         *     active recurring order applies on the next scheduled delivery.
         *
         *     `OPTIONS` returns `405 Allow: POST`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ItemDelta"][];
                };
            };
            responses: {
                /** @description Updated product list (same shape as GET) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductList"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListError"];
                    };
                };
                /** @description Unknown list */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ItemDelta: {
            /** @description Oda product ID */
            product_id: number;
            /**
             * @description Signed delta. Positive adds, negative removes. Negative beyond
             *     zero clamps at zero (item disappears from the list).
             */
            quantity: number;
        };
        /**
         * @description Decimal string, e.g. `"234.00"`. Currency is on the parent.
         * @example 234.00
         */
        Money: string;
        /** @description Product as embedded in cart and product-list items. */
        Product: {
            id?: number;
            full_name?: string;
            name?: string;
            /** @description Size or descriptor suffix */
            name_extra?: string;
            brand?: string | null;
            /** Format: uri */
            front_url?: string;
            /** @description Path-relative product URL */
            absolute_url?: string;
            gross_price?: components["schemas"]["Money"];
            gross_unit_price?: components["schemas"]["Money"];
            /** @description e.g. `"kg"`, `"l"` */
            unit_price_quantity_abbreviation?: string;
            /** @example NOK */
            currency?: string;
        };
        CartItem: {
            product: components["schemas"]["Product"];
            quantity: number;
        };
        Cart: {
            id?: number;
            product_quantity_count?: number;
            total_gross_amount?: components["schemas"]["Money"];
            /** @example NOK */
            currency?: string;
            /** @description Top-level items (rare; usually empty in favor of `groups`) */
            items?: components["schemas"]["CartItem"][];
            /** @description Items grouped by Oda's UI buckets. Flatten via `groups[].items`. */
            groups?: {
                items?: components["schemas"]["CartItem"][];
            }[];
        };
        /**
         * @description Tracking step name. Known values: `CONFIRMED`, `PACKING`, `EN_ROUTE`,
         *     `DELIVERED`, `CANCELLED`. Treated as open-ended because Oda may
         *     introduce new states; consumers map unknown values to a fallback
         *     ("OTHER" in our parsers). The lifecycle (per the `data.steps` array)
         *     is Bekreftet → Pakkes → På vei → Levert. Only `DELIVERED` and
         *     `CANCELLED` are terminal.
         * @example DELIVERED
         */
        OrderTrackingStep: string;
        OrderSummary: {
            /** @example 5fdnhy */
            order_number: string;
            /** Format: double */
            gross_amount?: number;
            /** @example NOK */
            currency?: string;
            delivery?: {
                delivery_address?: string;
                /** @description Human-readable string, e.g. `"man 1. desember, 18:53"`. */
                delivery_time?: string;
                status_text?: string;
                tracking?: {
                    step_name?: components["schemas"]["OrderTrackingStep"];
                };
            };
        };
        OrderMonth: {
            /** @example Desember 2025 */
            name?: string;
            /** @example month */
            type?: string;
            /** Format: double */
            gross_amount?: number;
            currency?: string;
            orders?: components["schemas"]["OrderSummary"][];
        };
        OrdersResponse: {
            get_more_url?: string | null;
            has_more?: boolean;
            results?: components["schemas"]["OrderMonth"][];
        };
        OrderLineItem: {
            product_id: number;
            description?: string;
            quantity?: number;
            /** Format: double */
            gross_amount?: number;
            currency?: string;
            front_url?: string | null;
            absolute_url?: string | null;
        };
        OrderItemGroup: {
            /** @example category */
            type?: string;
            /** @description Category name */
            name?: string;
            items?: components["schemas"]["OrderLineItem"][];
        };
        OrderDetail: {
            summary?: components["schemas"]["OrderSummary"];
            items?: {
                product_count?: number;
                item_groups?: components["schemas"]["OrderItemGroup"][];
            };
        };
        /**
         * @description Recurring schedule attached to a product list. `edit_url` carries
         *     the cadence as query params: `frequency` (weeks; 1=weekly,
         *     2=biweekly), `weekday` (ISO 1=Mon … 7=Sun), and an opaque
         *     `delivery_offering_id`.
         */
        RecurringOrderMeta: {
            id?: number;
            is_active?: boolean;
            /** Format: date */
            next_date?: string | null;
            /** @description Path with query params */
            edit_url?: string;
        };
        ProductListSummary: {
            id?: number;
            title?: string;
            description?: string;
            /** Format: uri */
            url?: string;
            number_of_products?: number;
            total_quantity?: number;
            eligible_for_recurring_order?: boolean;
            recurring_order?: components["schemas"]["RecurringOrderMeta"] | null;
        };
        ProductList: components["schemas"]["ProductListSummary"] & {
            is_recurring_order?: boolean;
            is_active_recurring_order?: boolean;
            currency?: string;
            items?: components["schemas"]["CartItem"][];
        };
        ProductListsPage: {
            next?: string | null;
            previous?: string | null;
            results?: components["schemas"]["ProductListSummary"][];
        };
        /**
         * @description Validation error shape from `/api/v1/product-lists/{id}/products/`.
         *     `errors` is an array of human-readable strings, e.g.
         *     `["Invalid product"]`. `field_errors` keys errors by field name.
         */
        ListError: {
            errors?: string[];
            field_errors?: {
                [key: string]: {
                    message?: string;
                    code?: string;
                };
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
